### ISSUE TITLE
cannot do "enable_triggers --force" in nanorc

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#10]
`enable_triggers` has no `--force` option it seems? Don't know if this is by design, but it could potentially be useful...

**Comment by plasorak** [comment]
Why would you want to enable triggers if you are in errors?

**Comment by wesketchum** [comment]
depends. E.g. if hermes or a wibmod died at some point during a run, I'm not certain that we expect them to do something depending on enabling or disabling of triggers, and we may want to allow that transition to be able to go through.

**Comment by wesketchum** [comment]
Will close for now. If a strong request for it returns, we can revisit.
