### ISSUE TITLE
Prevent run start in case the run registry insertion fails

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/ehn1-operations-issues#12]
In the past, when the run registry insertion at the start of the run was failing, nanorc would happily ignore that the microservice didnt manage to make the insertion. Do we want to prevent the run from starting if that's the case? Do we want to have a flag `--ignore-run-registry`?

**Comment by wesketchum** [comment]
I would say: yes, we do want this feature. For `nano04rc` this should be the default mode, with an option to ignore the run registry as you propose. For nanorc, perhaps it can be the opposite (default to ignore?).
