### ISSUE TITLE
Fatal(?) error on NICReceiver but still passed through transitions

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#14]
```
runp04srv028eth0 Readout Initialization Error: NICReceiver configuration failed due expected but unavailable interface!
```

Got this error in starting a run, but the configuration / start didn't actual fail in the transition and I was allowed to start/enable triggers. I've seen this error actually cause a configuration failure in the readout application before, but the circumstances here may have been different: there was another daq application that was using the NIC.

**Comment by alessandrothea** [comment]
Also, `NICReceiver` should fail configuration if the selected nic port is disconnected.
