### ISSUE TITLE
Grafana metric on main page not showing datawriters writing?

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#15]
<img width="772" alt="Screenshot 2024-02-09 at 13 32 28" src="https://github.com/DUNE-DAQ/ehn1-operations-issues/assets/5596636/0f86fdde-272e-4403-b90e-9517be018588">

Seeing 0 data being reported as written by data writers, even though data is being written.

**Comment by wesketchum** [comment]
(this was on partition np04hd, ~13:30 local time on 9 Feb 2024)

**Comment by mroda88** [comment]
I wish I understood what happened there, but I think I fixed in the v5.0.0 dashboards

**Comment by wesketchum** [comment]
Thanks. confirm that it's ok on the v5.0.0 dashboards. Will close this for now then.
