### ISSUE TITLE
'unable to push within timeout' from WIB streams at end of run

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#2]
Frequently at the end of runs with the cold electronics, see stream of ERROR messages like:

`wibeth_stream_100: Unable to push within timeout period (timeout period was 0 milliseconds)`

**Comment by wesketchum** [comment]
Coming from the readout application -- may be a race condition or a misordering in the stop transition. @roland-sipos and @bieryAtFnal to help followup.

**Comment by bieryAtFnal** [comment]
I found some log files with the reported error message in /log on np02-srv-002.  The most recent occurrence was on 01-Feb.  When I tried to pull down the configuration for a couple of the runs that had these errors from http://dunedaq-microservices:5005/runregistry/getRunBlob/23743, I got an internal server error.  I was hoping to see the queues in the readout app...

**Comment by wesketchum** [comment]
Ran this in runs this morning and saw this happen each time -- run 24191 is an example. Readout configuration is attached (from `/nfs/sw/dunedaq/dunedaq-fddaq-v4.3.0-rc1-dev/np04daq-configs/DAQ_CONFS/np04_daq_WIB_conf`).

[runp04srv028eth0_conf.json](https://github.com/DUNE-DAQ/ehn1-operations-issues/files/14260812/runp04srv028eth0_conf.json)

**Comment by bieryAtFnal** [comment]
Given what I see in the configuration, I believe that the two modules that are on either end of the queues that we see error messages about are NICReceiver and FDDataLinkHandler.

The latter does its end-run operations at the `stop_trigger_sources` transition.

The former does its end-run operations at the `stop` transition.

So, the queue consumer stops reading data off the queue at an earlier stop transition than the queue producer stops adding data to the queue.

We should check with Roland if it would be OK to change the binding of the NICReceiver::do_stop() method from the "stop" transition to the "stop_trigger_sources" transition ([here](https://github.com/DUNE-DAQ/dpdklibs/blob/23ffc9fef50f5850ad26a69ddcaccd1060dbb10a/plugins/NICReceiver.cpp#L63)), and it would be an interesting test to see if such a change helps anything.

**Comment by wesketchum** [comment]
@roland-sipos , can you comment here?

**Comment by roland-sipos** [comment]
As Kurt nicely captured the inconsistency between the modules doing stop/stop_trigger_sources, the only thing I can say is to let's try his proposal?

**Comment by bieryAtFnal** [comment]
For reference, [FelixCardReader](https://github.com/DUNE-DAQ/flxlibs/blob/9a0240fc4623f23af357f6080eb477663e761820/plugins/FelixCardReader.cpp#L59) uses the `stop_trigger_sources` transition for its `do_stop()` method.

And, the [FakeCardReader](https://github.com/DUNE-DAQ/fdreadoutmodules/blob/7bb687bf428784690fa298859470a00f6c4a416e/plugins/FDFakeCardReader.cpp#L54) uses the `drain_dataflow` transition, which is immediately before `stop_trigger_sources` in [the run control FSM](https://github.com/DUNE-DAQ/nanorc/blob/develop/docs/DUNE_FSM.drawio.png).

**Comment by alessandrothea** [comment]
Oh yeah, that explains it.

**Comment by wesketchum** [comment]
Should now be fixed as part of fddaq-v4.3.0-rc2

**Comment by wesketchum** [comment]
This is reappearing in fddaq-v4.3.0-rc2 ... @alessandrothea

**Comment by wesketchum** [comment]
I should be clear: this is running out of a fddaq-v4.3.0-rc2-based development area with dpdklibs "thea/workers_at_conf_v2" pulled down, and merged with the prep-release/fddaq-v4.3.0 branch.

**Comment by bieryAtFnal** [comment]
@wesketchum , looking at the logfile on srv-028 from today that had those errors, I saw lots of 'postprocessing backlog' messages and messages about late-arriving TPs at the tp_datahandler.  So, I wonder if the instances of the 'Unable to send' messages were prompted by a wider problem than the one that we fixed by moving the FSM transition for do_stop()...

**Comment by wesketchum** [comment]
Yeah, that could be. In three runs today with the fddaq-v4.3.0-rc3 release candidate, I did not see these messages at all, so I will re-close this ticket.

**Comment by wesketchum** [comment]
These seem to be reappearing in some recent runs.

```
wibeth_stream_300: Unable to push within timeout period (timeout period was 0 milliseconds)
```

e.g. on run 24642 and 246433, it was the above wibeth stream that had lots of complaints when the run was stpped.

**Comment by wesketchum** [comment]
Closing, as #34 largely covering this now.
