### ISSUE TITLE
Late data packets at start of run

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#21]
Prior to re-pinning the threads after run start (see #7 ), see a number of warnings from readout applications like:

```
Received a late data packet in run 24190, payload first timestamp = 106738809561945867, request_handler cutoff timestamp = 106738809564665867, difference = -2720000 ticks, -43.52 msec. -- 100 similar messages suppressed, last occurrence was at 2024-Feb-13 11:42:47,235168
```

**Comment by wesketchum** [comment]
This actually appears to occur _at_ the moment a pin_threads command is running/issued.

**Comment by plasorak** [comment]
Does waiting a little bit before starting the run work?

**Comment by wesketchum** [comment]
No, it doesn't matter. Also, I noticed today a slew of these messages at the start of the run, before I issues the pin_threads as well.

**Comment by wesketchum** [comment]
OK, this appeared in run 24302 _during_ the run for a brief moment as well.

Looking at the code, this check was added around 2 months ago, I think with the intention to better report on missed TP packets. (https://github.com/DUNE-DAQ/readoutlibs/commit/a88e0605ea9d73cac995dbb19a1382dbaafce499)

So a few things:
- It's not clear from the message where/which data packets are being dropped. It would be good if there was some way to clarify that.
- I'm not sure what the default is right now, but it may be that the cutoff/warning is a little too aggressive? Though maybe that depends on what's being dropped.
- It seems common that there is a bunch of these messages right in a row: I'm not sure how useful it is to see them at that frequency in the message reporting itself.

**Comment by wesketchum** [comment]
@bieryAtFnal will plan to add in the SourceID to the message to help better understand things. Will also plan to put the absolute time.

Should test if this also happens if we issue a pin_threads again, to see if it's only when we're changing the pinning configuration (vs. just repinning but to the same CPUs). That will inform what a solution may be for getting rid of the warning messages at start.

**Comment by wesketchum** [comment]
Just issued a `pin_threads` command a few times while running, using the same pinning file. Saw the warning messages reappear each time on all four TPC readout servers.

**Comment by bieryAtFnal** [comment]
I've made some progress on improving the warning message that is printed out when the tp_datahandler sees that TriggerPrimitives will not be sent to the Trigger because they were tardy.

Here is an example of the new message:

- `SourceID[subsystem: Trigger id: 0] Received a late data packet in run 101, the packet arrived 1.31072 msec later than the allowed latency window of 20 msec (1250000 ticks).`
    - Please note that this is just a sample.  The default value of the allowed latency window in our system is 50 msec, and the 20 msec value mentioned above was just used in a special test of the software.
    - Another note is that it is possible to see a value of 0 msec too late (e.g. the packet arrived 0 msec later...) .  This just means that the packet was exactly at the boundary of the allowed latency window, and I have verified that it truly does not get sent to the Trigger.

For reference, here is an example of the existing message:

- `Received a late data packet in run 101, payload first timestamp = 79554163131560263, request_handler cutoff timestamp = 79554163131642183, difference = -81920 ticks, -1.31072 msec.`

If there are suggestions for improving the warning message further, I can work to implement them.

We can discuss this at the Operations call on Tuesday, 05-March.  And, if these improvements seem reasonable, I can create Pull Requests in `readoutlibs` and `fdreadoutlibs`.

**Comment by wesketchum** [comment]
Should investigate why we had problems with pinning after conf -- need to confirm when the postprocessor threads are named (if they are done at start, potential problem there...)

**Comment by wesketchum** [comment]
proposed shortening of message:

```
SourceID[Trigger id: 0] Received late data packet from TP <channel>, 1.31072 ms after allowed latency (20 ms, 1250000 ticks).
```

**Comment by bieryAtFnal** [comment]
Based on the feedback from multiple people about the contents of the message, here is the current draft:
```
SourceID[Trigger,0] Received late data packet, TP channel 6132, 0.98304 ms beyond the allowed latency (20 ms, 1250000 ticks)
```

Thinking ahead to the next step, i.e. suppressing the warning messages at the start of runs, a question:  do we just want to suppress the messages or completely turn off any checking for tardy TPs for some number of seconds at the start of each run?

Where this matters will be in the operational monitoring metrics.  If we suppress all checking for tardy TPs at the start of the run, then the `num_tps_suppressed_tardy` metric will have a zero value for all runs that don't have any tardy TPs beyond the first few seconds of a run.  If we just suppress the warning messages, the count of tardy TPs from the start of the run *will* be included in the reported metric value.

**Comment by wesketchum** [comment]
Fixes are in place on production/v4, and is working. closing.
