### ISSUE TITLE
Record command doesn't work remotely

### ISSUE THREAD

**Issue by matthew-man-457** [DUNE-DAQ/ehn1-operations-issues#24]
When sending the record command in nanorc from the run control server np04-srv-024 to the readout server np02-srv-003, nothing is populated into the recording output directory. When running nanorc locally at the readout server, the recording output is indeed populated.

The daqconf is set to:
```
"enable_raw_recording": true,
"raw_recording_output_dir": "/mnt/nvm_raid0/np04daq/",
```
I've also tried `"raw_recording_output_dir": "np02-srv-003:/mnt/nvm_raid0/np04daq/",`

**Comment by wesketchum** [comment]
For clarity: when sending command from nanorc on np02-srv-003 to np02-srv-003 it works, but from np04-srv-024 to np02-srv-003 it is not populating properly, but no error is appearing from nanorc.

Should check connectivity between np04-srv-024 and np02-srv-003 (e.g. use curl once system is up).

**Comment by matthew-man-457** [comment]
This was a permissions issue to the disk on np02-srv-003. the np04daq user has been added, so it is now resolved.
