### ISSUE TITLE
Sampling not optimized for data writers information plot?

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#25]
From the DAQ Overview page, when running at 10Hz trigger rate it looked like the sampling was not quite optimized, leading to some large variations in the sum plot.
<img width="1683" alt="Screenshot 2024-02-23 at 10 33 22" src="https://github.com/DUNE-DAQ/ehn1-operations-issues/assets/5596636/6294e659-3a9a-4412-83e6-5289a5a584fe">

**Comment by mroda88** [comment]
Fixed. I changed the way the total is calculated. Instead of being generated by grafana, it's calculated with a query. So the oscillation disappeared. 
![Screenshot from 2024-02-23 13-16-02](https://github.com/DUNE-DAQ/ehn1-operations-issues/assets/31312964/57620dea-cc5c-42ba-b57a-ba2fece3685c)

**Comment by wesketchum** [comment]
thanks Marco!
