### ISSUE TITLE
detaching from tmux caused run to stop for user

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#26]
Sophie reported that when she detached form the np04_hd tmux session (as np04daq user), that the run stopped, with a core dump reported from nano04rc. Happened again when she tried to repeat it, but we haven't further investigated. Will be good to followup and resolve in case this happens with other users.

**Comment by sbutchart** [comment]
The issue was caused by a mismatch in keybindings causing `Ctrl-\` to send a `SIGQUIT` rather than detaching from the tmux session - we fixed it by implementing a catch for `SIGQUIT` in nanorc that can be found [here](https://github.com/DUNE-DAQ/nanorc/pull/251).
