### ISSUE TITLE
HugePages on np04-srv-021

### ISSUE THREAD

**Issue by TiagoTAlves** [DUNE-DAQ/ehn1-operations-issues#28]
When running nanorc with kubernetes, the configuration requests 8Gb for HugePages on the `runp04srv021eth0` but the node that it runs on only has 4Gb available.

We may need to change this at configuration generation.

**Comment by wesketchum** [comment]
Addressed in this PR: https://github.com/DUNE-DAQ/fddaqconf/pull/25
