### ISSUE TITLE
Changes to recreate* configuration scripts for backups and tp-file-labels

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/ehn1-operations-issues#29]
I have modified copies of the following recreate* configuration scripts.  The modified copies are on the np04 cluster in directory `/nfs/sw/dunedaq/dunedaq-fddaq-v4.3.0-rc3-dev/np04daq-configs`.

- recreate_np04_daq_configurations.sh
- recreate_np04_daq_k8s_configurations.sh
- recreate_wib_configurations.sh

The changes that I have made are the following:

1. added functionality to back up each configuration directory that is being re-created so that the backup can be use for comparisons and other reference
2. added the --tp-file-label argument to the `fddaqconf_gen` script, where appropriate, in order to properly set the TPStream file prefix

I have *not* yet deployed any of these modified scripts to software areas that are in current use.  I'll leave that to folks who are resident at CERN.

One implementation note is that there is a sanity check in these scripts that verifies whether a config directory that has been requested to be backed up doesn't exist, a message is printed to the console.  I hope that this will be useful in catching typos within the recreate* scripts and problems in running `fddaqconf_gen` and similar scripts.

**Comment by wesketchum** [comment]
This should now be running in both the master and @TiagoTAlves 's K8s testing branch at NP04. Will try to advertise and make sure we're capturing everything else.
