### ISSUE TITLE
trigger producing large logs

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#32]
We filled up the `/` volume on np04-srv-002 recently, largely driven by size of log files. `trigger` logs seems to be producing a lot of messages: is it possible to evaluate and remove some of these log messages for 'normal' running?

**Comment by MRiganSUSX** [comment]
Fixed by 
https://github.com/DUNE-DAQ/trigger/pull/285
https://github.com/DUNE-DAQ/triggeralgs/pull/59
