### ISSUE TITLE
Update to pinning sequence

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/ehn1-operations-issues#7]
Due to the configuration issues on threading in the ethernet readout, we need to apply separate pinning files from config through run start to enabling triggers. A typical sequence is like:

```
boot
pin_threads <conf_pining_file>
conf
start
pin_threads <running_pinning_file>
enable_triggers
```

It would be good to reflect this in the `start_run` command, and likely provide in configuration two pinning files: one for conf and one for running.

**Comment by plasorak** [comment]
https://github.com/DUNE-DAQ/nanorc/pull/243 and https://github.com/DUNE-DAQ/fddaqconf/pull/20 should allow full configurability of the thread pinning script execution in the configuration.

**Comment by wesketchum** [comment]
working properly (I think) in the fddaq-v4.3.0-rc3 release candidate
